
/*actions-type */
export const GET_DRIVER = "GET_DRIVER";
export const GET_TEAM = "GET_TEAM";
export const GET_DRIVER_DETAIL = "GET_DRIVER_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SEARCH_DRIVERS_BY_NAME = 'SEARCH_DRIVERS_BY_NAME';
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const SORT_DRIVERS_BY_NAME = 'SORT_DRIVERS_BY_NAME';
export const SORT_DRIVERS_BY_DOB = 'SORT_DRIVERS_BY_DOB';
export const FILTER_DRIVERS_BY_ORIGIN= 'FILTER_DRIVERS_BY_ORIGIN'
export const FILTER_DRIVERS_BY_TEAM= 'FILTER_DRIVERS_BY_TEAM'
export const ADD_DRIVER = "ADD_DRIVER";



